apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: sysdig-vm-dashboard
  labels:
    app: clickhouse
spec:
  ports:
  - port: 8123
    name: "http-connection"
  - port: 9000
    name: "native-connection"
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
  namespace: sysdig-vm-dashboard
  labels:
    app: clickhouse
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
    - name: http-connection
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30812  # This must be in the range 30000-32767
    - name: native-connection
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900  # Also in the valid range